FROM python:3.10
WORKDIR /app
COPY . .
# RUN apt-get update && apt-get upgrade -y
# RUN  curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/
#get-poetry.py | python -
#RUN bash -c "source $HOME/.poetry/env"
RUN pip install poetry
RUN poetry install --no-root
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

