from . import admin
from . import client
from . import expense
from . import invoice
from . import payment
from . import real_training
from . import student
from . import subscription
from . import trainer
from . import trainer_training_type_salary
from . import training
from . import training_template
from . import training_type
from . import user