"""global change of the user structure

Revision ID: 0df6641123b7
Revises: c64106e4a3ac
Create Date: 2025-04-16 17:00:48.957429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0df6641123b7'
down_revision: Union[str, None] = 'c64106e4a3ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('has_trial', sa.Boolean(), nullable=True),
    sa.Column('birth_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.alter_column('client_subscriptions', 'sessions_left',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('client_subscriptions_client_id_fkey', 'client_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'client_subscriptions', 'clients', ['client_id'], ['id'])
    op.add_column('invoices', sa.Column('client_training_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'training_clients', ['client_training_id'], ['id'])
    op.add_column('training_clients', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('training_clients_client_id_fkey', 'training_clients', type_='foreignkey')
    op.create_foreign_key(None, 'training_clients', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'training_clients', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('is_client', sa.Boolean(), nullable=True))
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'has_trial')
    op.drop_column('users', 'parent_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('parent_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('has_trial', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('birth_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_client')
    op.drop_constraint(None, 'training_clients', type_='foreignkey')
    op.drop_constraint(None, 'training_clients', type_='foreignkey')
    op.create_foreign_key('training_clients_client_id_fkey', 'training_clients', 'users', ['client_id'], ['id'])
    op.drop_column('training_clients', 'user_id')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'client_training_id')
    op.drop_constraint(None, 'client_subscriptions', type_='foreignkey')
    op.create_foreign_key('client_subscriptions_client_id_fkey', 'client_subscriptions', 'users', ['client_id'], ['id'])
    op.alter_column('client_subscriptions', 'sessions_left',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
