"""remove created_by_id from invoice

Revision ID: 0ffeab69753f
Revises: 22e3eb875091
Create Date: 2025-07-07 14:45:52.634292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ffeab69753f'
down_revision: Union[str, None] = '22e3eb875091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invoices_created_by_id_fkey'), 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'created_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('invoices_created_by_id_fkey'), 'invoices', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###
