"""add is_trial to real_training_student

Revision ID: 127bf1952a11
Revises: 6dfa2c5854c1
Create Date: 2025-09-22 16:35:39.510245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '127bf1952a11'
down_revision: Union[str, None] = '6dfa2c5854c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_training_students', sa.Column('is_trial', sa.Boolean(), nullable=True))
    op.execute('UPDATE real_training_students SET is_trial = false')
    op.alter_column('real_training_students', 'is_trial', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('real_training_students', 'is_trial')
    # ### end Alembic commands ###
