"""test

Revision ID: 21fd980e45ae
Revises: c6d5f27ad382
Create Date: 2025-04-09 15:42:28.726288

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '21fd980e45ae'
down_revision: Union[str, None] = 'c6d5f27ad382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
