"""reworked payments and invoices

Revision ID: 223cc5fe592e
Revises: ec55543222cc
Create Date: 2025-05-21 20:01:52.095472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223cc5fe592e'
down_revision: Union[str, None] = 'ec55543222cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invoices_payment_id_fkey', 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'payment_id')
    op.add_column('payment_history', sa.Column('invoice_id', sa.Integer(), nullable=True))
    op.alter_column('payment_history', 'payment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'payment_history', 'invoices', ['invoice_id'], ['id'])
    op.add_column('real_training_students', sa.Column('requires_payment', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('real_training_students', 'requires_payment')
    op.drop_constraint(None, 'payment_history', type_='foreignkey')
    op.alter_column('payment_history', 'payment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('payment_history', 'invoice_id')
    op.add_column('invoices', sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('invoices_payment_id_fkey', 'invoices', 'payments', ['payment_id'], ['id'])
    # ### end Alembic commands ###
