"""extend_attendance_status_with_cancellation_types

Revision ID: 22e3eb875091
Revises: dc6312ac6dc3
Create Date: 2025-07-03 15:51:11.137378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22e3eb875091'
down_revision: Union[str, None] = 'dc6312ac6dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем новые значения в enum AttendanceStatus
    op.execute("ALTER TYPE attendancestatus ADD VALUE IF NOT EXISTS 'CANCELLED_SAFE'")
    op.execute("ALTER TYPE attendancestatus ADD VALUE IF NOT EXISTS 'CANCELLED_PENALTY'")
    op.execute("ALTER TYPE attendancestatus ADD VALUE IF NOT EXISTS 'REGISTERED'")
    op.execute("ALTER TYPE attendancestatus ADD VALUE IF NOT EXISTS 'WAITLIST'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаление значений из enum невозможно в PostgreSQL без пересоздания типа
    # Оставляем пустым, так как это breaking change
    pass
    # ### end Alembic commands ###
