"""added active field to subscriptions

Revision ID: 2986b4aa7af9
Revises: b9585db5101c
Create Date: 2025-03-23 12:57:24.052355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2986b4aa7af9'
down_revision: Union[str, None] = 'b9585db5101c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'active')
    # ### end Alembic commands ###
