"""added client balances

Revision ID: 364957d0c94e
Revises: 5731f8e1c0d2
Create Date: 2025-04-15 19:17:29.638251

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '364957d0c94e'
down_revision: Union[str, None] = '5731f8e1c0d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE users SET balance = 0 WHERE role = 'CLIENT'")

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###
