"""add_skipped_sessions_to_student_subscription

Revision ID: 39789ed8bd05
Revises: b658dc62f155
Create Date: 2025-09-15 23:21:14.244399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39789ed8bd05'
down_revision: Union[str, None] = 'b658dc62f155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_subscriptions', sa.Column('skipped_sessions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_subscriptions', 'skipped_sessions')
    # ### end Alembic commands ###
