"""Add is_active field to training_type

Revision ID: 50d1ad23c6ce
Revises: 1f12ef6834bf
Create Date: 2025-05-17 03:08:43.471588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d1ad23c6ce'
down_revision: Union[str, None] = '1f12ef6834bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_types', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_types', 'is_active')
    # ### end Alembic commands ###
