"""change enum name

Revision ID: 55ca1ca6ddeb
Revises: 42a728f4223f
Create Date: 2025-03-15 17:30:31.036417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55ca1ca6ddeb'
down_revision: Union[str, None] = '42a728f4223f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE TYPE user_role_enum AS ENUM ('CLIENT', 'TRAINER', 'ADMIN')")

    op.execute("""
           ALTER TABLE users
           ALTER COLUMN role TYPE TEXT
       """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
            ALTER TABLE users
            ALTER COLUMN role TYPE user_role_enum
            USING role::user_role_enum
        """)

    # ### end Alembic commands ###
    op.execute("DROP TYPE trainingtypeenum")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('CLIENT', 'TRAINER', 'ADMIN', name='user_role_enum'),
               type_=postgresql.ENUM('CLIENT', 'TRAINER', 'ADMIN', name='trainingtypeenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
