"""Add client_id to invoices and make student_id optional

Revision ID: 55f55348696d
Revises: 7471c86776e8
Create Date: 2025-05-19 01:35:15.119255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f55348696d'
down_revision: Union[str, None] = '7471c86776e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('client_id', sa.Integer(), nullable=False))
    op.alter_column('invoices', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'invoices', 'users', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.alter_column('invoices', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('invoices', 'client_id')
    # ### end Alembic commands ###
