"""added has_trial field to client

Revision ID: 5731f8e1c0d2
Revises: 0d1965cd6238
Create Date: 2025-04-15 13:00:48.943884

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5731f8e1c0d2'
down_revision: Union[str, None] = '0d1965cd6238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payments_subscription_id_fkey', 'payments', type_='foreignkey')
    op.drop_column('payments', 'subscription_id')
    op.add_column('users', sa.Column('has_trial', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET has_trial = true WHERE role = 'CLIENT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_trial')
    op.add_column('payments', sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('payments_subscription_id_fkey', 'payments', 'subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###
