"""add_borrowed_sessions_to_student_subscription

Revision ID: 5a4d28dfcab9
Revises: 39789ed8bd05
Create Date: 2025-09-16 00:12:59.274447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a4d28dfcab9'
down_revision: Union[str, None] = '39789ed8bd05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_subscriptions', sa.Column('borrowed_sessions_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_subscriptions', 'borrowed_sessions_count')
    # ### end Alembic commands ###
