"""remove_student_monthly_stats

Revision ID: 606903883f5f
Revises: 9efc80b025ce
Create Date: 2025-05-19 20:54:45.322665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '606903883f5f'
down_revision: Union[str, None] = '9efc80b025ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_monthly_stats_id', table_name='student_monthly_stats')
    op.drop_table('student_monthly_stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_monthly_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year_month', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('rescheduled_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='student_monthly_stats_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='student_monthly_stats_pkey'),
    sa.UniqueConstraint('student_id', 'year_month', name='unique_student_month')
    )
    op.create_index('ix_student_monthly_stats_id', 'student_monthly_stats', ['id'], unique=False)
    # ### end Alembic commands ###
