"""Add is_salary_processed to RealTraining

Revision ID: 6dfa2c5854c1
Revises: 8da986c48d54
Create Date: 2025-09-21 02:59:09.214959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dfa2c5854c1'
down_revision: Union[str, None] = '8da986c48d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_trainings', sa.Column('is_salary_processed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('real_trainings', 'is_salary_processed')
    # ### end Alembic commands ###
