"""added_trainer_training_type_salary_table

Revision ID: 6fd235039f71
Revises: ffbdbe85c7c2
Create Date: 2025-08-09 08:57:57.413087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd235039f71'
down_revision: Union[str, None] = 'ffbdbe85c7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer_training_type_salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('training_type_id', sa.Integer(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['training_type_id'], ['training_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainer_id', 'training_type_id', name='uq_trainer_training_type')
    )
    op.create_index(op.f('ix_trainer_training_type_salaries_id'), 'trainer_training_type_salaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainer_training_type_salaries_id'), table_name='trainer_training_type_salaries')
    op.drop_table('trainer_training_type_salaries')
    # ### end Alembic commands ###
