"""added comments to invoices

Revision ID: 7162e5e2e8f3
Revises: 127bf1952a11
Create Date: 2025-11-14 16:23:25.877946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7162e5e2e8f3'
down_revision: Union[str, None] = '127bf1952a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'comment')
    # ### end Alembic commands ###
