"""added trainings table

Revision ID: 7fa69ee03ec5
Revises: b634168e1033
Create Date: 2025-03-19 21:29:44.491786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa69ee03ec5'
down_revision: Union[str, None] = 'b634168e1033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_types', sa.Column('created_at', sa.Date(), nullable=False))
    op.add_column('training_types', sa.Column('updated_at', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_types', 'updated_at')
    op.drop_column('training_types', 'created_at')
    # ### end Alembic commands ###
