"""subscriptions_v2_additive

Revision ID: 82747771ed7b
Revises: 7162e5e2e8f3
Create Date: 2026-03-01 13:05:37.039149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82747771ed7b'
down_revision: Union[str, None] = '7162e5e2e8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('missed_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_subscription_id', sa.Integer(), nullable=False),
    sa.Column('real_training_student_id', sa.Integer(), nullable=False),
    sa.Column('is_excused', sa.Boolean(), nullable=False),
    sa.Column('excused_by_id', sa.Integer(), nullable=True),
    sa.Column('excused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('makeup_deadline_date', sa.Date(), nullable=True),
    sa.Column('made_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('made_up_real_training_student_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['excused_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['made_up_real_training_student_id'], ['real_training_students.id'], ),
    sa.ForeignKeyConstraint(['real_training_student_id'], ['real_training_students.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['student_subscription_id'], ['student_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('real_training_student_id')
    )
    op.create_index(op.f('ix_missed_sessions_id'), 'missed_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_missed_sessions_student_id'), 'missed_sessions', ['student_id'], unique=False)
    op.create_index(
        'idx_missed_sessions_excused',
        'missed_sessions',
        ['student_id', 'is_excused', 'made_up_at', 'makeup_deadline_date'],
    )
    op.add_column('invoices', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('student_subscriptions', sa.Column('payment_due_date', sa.Date(), nullable=True))
    op.add_column('student_subscriptions', sa.Column('is_prorated', sa.Boolean(), nullable=True))
    op.add_column('subscriptions', sa.Column('sessions_per_week', sa.Integer(), nullable=True))

    # Начальные значения системных настроек
    op.execute("INSERT INTO system_settings (key, value) VALUES ('makeup_window_days', '90')")
    op.execute("INSERT INTO system_settings (key, value) VALUES ('debt_behavior', 'HIGHLIGHT_ONLY')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'sessions_per_week')
    op.drop_column('student_subscriptions', 'is_prorated')
    op.drop_column('student_subscriptions', 'payment_due_date')
    op.drop_column('invoices', 'due_date')
    op.drop_index(op.f('ix_missed_sessions_student_id'), table_name='missed_sessions')
    op.drop_index(op.f('ix_missed_sessions_id'), table_name='missed_sessions')
    op.drop_index('idx_missed_sessions_excused', table_name='missed_sessions')
    op.drop_table('missed_sessions')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
