"""Add country code for phone numbers

Revision ID: 88430763c582
Revises: 7e1d397e5329
Create Date: 2025-07-21 09:24:40.492149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88430763c582'
down_revision: Union[str, None] = '7e1d397e5329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_country_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('whatsapp_country_code', sa.String(), nullable=True))

    op.execute("""
        UPDATE users
        SET phone_country_code = '+421',
            phone_number = phone
        WHERE phone IS NOT NULL
    """)

    op.alter_column('users', 'phone_country_code', nullable=False)
    op.alter_column('users', 'phone_number', nullable=False)

    op.drop_constraint('users_phone_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['phone_number'])
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))

    op.execute("""
        UPDATE users
        SET phone = phone_country_code || phone_number
    """)

    op.alter_column('users', 'phone', nullable=False)

    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    op.drop_column('users', 'whatsapp_country_code')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'phone_country_code')
    # ### end Alembic commands ###
