"""reworked training models

Revision ID: 930dc2933e00
Revises: dbdcf496e0ec
Create Date: 2025-04-12 03:19:42.100264

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '930dc2933e00'
down_revision: Union[str, None] = 'dbdcf496e0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_clients', 'covered_by_subscription')
    op.add_column('trainings', sa.Column('training_datetime', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('trainings', 'training_date')
    op.drop_column('trainings', 'training_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('training_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('trainings', sa.Column('training_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('trainings', 'training_datetime')
    op.add_column('training_clients', sa.Column('covered_by_subscription', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
