"""added training constraints

Revision ID: 937d9bda9a5b
Revises: 930dc2933e00
Create Date: 2025-04-12 17:58:07.978089

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '937d9bda9a5b'
down_revision: Union[str, None] = '930dc2933e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_trainer_training_datetime', 'trainings', ['trainer_id', 'training_datetime'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_trainer_training_datetime', 'trainings', type_='unique')
    # ### end Alembic commands ###
