"""Add training_id and make subscription_id optional in invoices

Revision ID: 93b332870135
Revises: 55f55348696d
Create Date: 2025-05-19 01:38:14.630672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b332870135'
down_revision: Union[str, None] = '55f55348696d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('training_id', sa.Integer(), nullable=True))
    op.alter_column('invoices', 'subscription_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'invoices', 'real_trainings', ['training_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.alter_column('invoices', 'subscription_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('invoices', 'training_id')
    # ### end Alembic commands ###
