"""added created_at field for user

Revision ID: b634168e1033
Revises: b67c04a7c4cb
Create Date: 2025-03-16 03:22:35.144082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b634168e1033'
down_revision: Union[str, None] = 'b67c04a7c4cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.Date(), nullable=False, server_default=sa.func.current_date()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
