"""Add session_deducted to RealTrainingStudent

Revision ID: b658dc62f155
Revises: 5ed24a9fbf1f
Create Date: 2025-09-15 20:52:03.766219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b658dc62f155'
down_revision: Union[str, None] = '5ed24a9fbf1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_training_students', sa.Column('session_deducted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('real_training_students', 'session_deducted')
    # ### end Alembic commands ###
