"""added active field to client

Revision ID: b67c04a7c4cb
Revises: 55ca1ca6ddeb
Create Date: 2025-03-15 22:52:14.458347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67c04a7c4cb'
down_revision: Union[str, None] = '55ca1ca6ddeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.execute(sa.text("UPDATE users SET active = true"))
    op.alter_column('users', 'active', server_default=None)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active')
    # ### end Alembic commands ###
