"""test change

Revision ID: b89b2fcbfb2a
Revises: 1119e30ecf91
Create Date: 2025-04-09 19:10:15.436678

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b89b2fcbfb2a'
down_revision: Union[str, None] = '1119e30ecf91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE client_subscriptions
        ALTER COLUMN start_date TYPE TIMESTAMP WITH TIME ZONE
        USING start_date::TIMESTAMP WITH TIME ZONE;
        """
    )
    # Alter `end_date` with a USING clause to convert VARCHAR -> TIMESTAMP WITH TIME ZONE
    op.execute(
        """
        ALTER TABLE client_subscriptions
        ALTER COLUMN end_date TYPE TIMESTAMP WITH TIME ZONE
        USING end_date::TIMESTAMP WITH TIME ZONE;
        """
    )


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE client_subscriptions
        ALTER COLUMN start_date TYPE VARCHAR
        USING start_date::TEXT;
        """
    )
    # Reverse the `end_date` column type back to VARCHAR
    op.execute(
        """
        ALTER TABLE client_subscriptions
        ALTER COLUMN end_date TYPE VARCHAR
        USING end_date::TEXT;
        """
    )

# ### end Alembic commands ###
