"""added title to ssubscriptions

Revision ID: b9585db5101c
Revises: c8d4bd376340
Create Date: 2025-03-23 01:36:02.512574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9585db5101c'
down_revision: Union[str, None] = 'c8d4bd376340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('title', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'subscriptions', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_column('subscriptions', 'title')
    # ### end Alembic commands ###
