"""update time settings on models

Revision ID: baeb91bbc39d
Revises: e7cb7521d920
Create Date: 2025-05-13 15:51:14.307672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baeb91bbc39d'
down_revision: Union[str, None] = 'e7cb7521d920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_templates', sa.Column('start_time', sa.Time(), nullable=False))
    op.drop_index('idx_day_time', table_name='training_templates')
    op.create_index('idx_day_time', 'training_templates', ['day_number', 'start_time'], unique=False)
    op.drop_column('training_templates', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_templates', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_index('idx_day_time', table_name='training_templates')
    op.create_index('idx_day_time', 'training_templates', ['day_number', 'time'], unique=False)
    op.drop_column('training_templates', 'start_time')
    # ### end Alembic commands ###
