"""Add trainer_salary_eligible field to real_trainings

Revision ID: bcd41458ec9d
Revises: a05a539b0fd1
Create Date: 2025-09-08 16:43:35.623181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd41458ec9d'
down_revision: Union[str, None] = 'a05a539b0fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_trainings', sa.Column('trainer_salary_eligible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('real_trainings', 'trainer_salary_eligible')
    # ### end Alembic commands ###
