"""add_processed_at_to_real_trainings

Revision ID: bd594d2a0480
Revises: 0ffeab69753f
Create Date: 2025-07-09 02:40:54.720095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd594d2a0480'
down_revision: Union[str, None] = '0ffeab69753f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_trainings', sa.Column('processed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('real_trainings', 'processed_at')
    # ### end Alembic commands ###
