"""added subscription duration

Revision ID: c6d5f27ad382
Revises: e2edb244a9a0
Create Date: 2025-04-07 12:41:08.505764

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c6d5f27ad382'
down_revision: Union[str, None] = 'e2edb244a9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_subscriptions', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('subscriptions', sa.Column('duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'duration')
    op.alter_column('client_subscriptions', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
