"""added training_type_price

Revision ID: c8d4bd376340
Revises: f60c24fdab4f
Create Date: 2025-03-23 01:16:09.354579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8d4bd376340'
down_revision: Union[str, None] = 'f60c24fdab4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_types', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_types', 'price')
    # ### end Alembic commands ###
