"""added index

Revision ID: d3aadbe2a70e
Revises: b89b2fcbfb2a
Create Date: 2025-04-09 19:45:33.438065

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd3aadbe2a70e'
down_revision: Union[str, None] = 'b89b2fcbfb2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_client_active_subscription', 'client_subscriptions', ['client_id'], unique=True, postgresql_where=sa.text('active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_client_active_subscription', table_name='client_subscriptions', postgresql_where=sa.text('active = true'))
    # ### end Alembic commands ###
