"""added max participants

Revision ID: dc6312ac6dc3
Revises: 0b9e03a09cdb
Create Date: 2025-06-05 20:14:31.792263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc6312ac6dc3'
down_revision: Union[str, None] = '0b9e03a09cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_types', sa.Column('max_participants', sa.Integer(), server_default=sa.text('4'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_types', 'max_participants')
    # ### end Alembic commands ###
