"""Add student_subscription_id to Invoice model

Revision ID: e064b77658d4
Revises: bd594d2a0480
Create Date: 2025-07-11 19:50:03.362642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e064b77658d4'
down_revision: Union[str, None] = 'bd594d2a0480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('student_subscription_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'student_subscriptions', ['student_subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'student_subscription_id')
    # ### end Alembic commands ###
